<?php

namespace AppBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * CompetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitionRepository extends EntityRepository
{
    /**
     * @param array $options
     *
     * @return mixed
     */
    public function findAllOrderedByDate(array $options = [])
    {
        $defaultOptions = [
            'order' => 'DESC',
            'limit' => null,
        ];
        $options = array_merge($defaultOptions, $options);

        $dql = "SELECT c, htm, atm FROM AppBundle:Competition c
            LEFT JOIN c.homeTeam htm
            LEFT JOIN c.awayTeam atm
            WHERE c.homeTeam = htm.id OR c.awayTeam = atm.id
            ORDER BY c.startAt {$options['order']}";

        $result = $this->getEntityManager()
            ->createQuery($dql)
            ->setMaxResults($options['limit'])
            ->getResult();

        return $result;
    }
}
