imports:
    - { resource: config_dev.yml }

services:
    _defaults:
        public: true
    test.AppBundle\Service\SoccerWayService: '@AppBundle\Service\SoccerWayService'
    test.AppBundle\Service\DomCrawlerService: '@AppBundle\Service\DomCrawlerService'

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        url: 'sqlite:///%kernel.project_dir%/var/data/test.sqlite'

liip_functional_test: ~
